openapi: 3.0.0
info:
  title: Gestão de Produtos Perecíveis
  description: |
    API de produtos perecíveis.
    Encontra aqui os produtos perecíveis que estão perto do fim de validade e contribui para a redução de alimentos desperdiçados
    url: https://virtserver.swaggerhub.co
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /
tags:
- name: produto
  description: Operação de produtos perecíveis
- name: utilizador
  description: Operação dos utilizadores
paths:
  /produto:
    get:
      tags:
      - produto
      summary: Listar todos os produtos
      description: Retorna todos os produtos na base dados
      operationId: getListProdutos
      responses:
        "200":
          description: Lista de produtos enviados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
        "400":
          description: Erro ao enviar lista
        "404":
          description: Não existem produtos na base de dados
      x-swagger-router-controller: Produto
    post:
      tags:
      - produto
      summary: Adicionar um novo produto
      operationId: postProduto
      requestBody:
        $ref: '#/components/requestBodies/Produto'
      responses:
        "200":
          description: Produto adicionado com sucesso
        "400":
          description: Request body do produto invalido
        "401":
          description: Sem autorização
      security:
      - bearerAuth: []
      x-swagger-router-controller: Produto
  /produto/{produtoId}:
    get:
      tags:
      - produto
      summary: Encontrar um produto pelo produtoId
      description: Retorna um único produto mais detalhado
      operationId: getProduto
      parameters:
      - name: produtoId
        in: path
        description: produtoId necessário
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Produto enviado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
            application/xml:
              schema:
                $ref: '#/components/schemas/Produto'
        "400":
          description: Erro no envio da informação do produto
        "404":
          description: "Produto não encontrado {produtoId invalido}"
      x-swagger-router-controller: Produto
    put:
      tags:
      - produto
      summary: Atualizar um produto através do produtoId
      description: Atualiza um produto
      operationId: putProduto
      parameters:
      - name: produtoId
        in: path
        description: produtoId necessário
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        $ref: '#/components/requestBodies/Produto'
      responses:
        "200":
          description: Produto atualizado com sucesso
        "400":
          description: Erro na atualização do produto
        "404":
          description: "Produto não encontrado {produtoId invalido}"
      security:
      - bearerAuth: []
      x-swagger-router-controller: Produto
    delete:
      tags:
      - produto
      summary: Eliminar um produto pelo produtoId
      operationId: deleteProduto
      parameters:
      - name: produtoId
        in: path
        description: produtoId necessário para eliminar
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Produto eliminado com sucesso
        "400":
          description: produtoId invalido
        "404":
          description: Produto não encontrado
      security:
      - bearerAuth: []
      x-swagger-router-controller: Produto
  /produto/listPrecoMedio:
    get:
      tags:
      - produto
      summary: Listar produtos com o preço medio
      description: Retorna todos os produtos e o seu preço medio
      operationId: getListPrecoMedio
      responses:
        "200":
          description: Lista dos produtos com o preco medio enviado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaPrecoMedio'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaPrecoMedio'
        "400":
          description: Erro ao enviar a lista
        "404":
          description: Não existem produtos na base dados
      x-swagger-router-controller: Produto
  /produto/findByCategoria/{categoria}:
    get:
      tags:
      - produto
      summary: Encontrar produtos por categoria
      description: Múltiplos produtos enviados consoante a categoria selecionada
      operationId: getProdutoByCategoria
      parameters:
      - name: categoria
        in: path
        description: É necessário o envio da categoria para puder ser enviado a lista
          de produtos correta
        required: true
        style: simple
        explode: true
        schema:
          type: array
          items:
            type: string
            default: todos
      responses:
        "200":
          description: Lista de produtos enviado consoante a categoria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutos'
        "400":
          description: Invalido
        "404":
          description: Categoria não foi encontrado
      x-swagger-router-controller: Produto
  /produto/listarNaoDesperdicados:
    get:
      tags:
      - produto
      summary: Listar todos os produtos e as suas quantidades não desperdiçadas
      description: "Listar todos os produtos e as suas quantidades não desperdiçadas,\
        \ divido por peso liquido e peso bruto"
      operationId: getListProdutosNaoDesperdicados
      responses:
        "200":
          description: Lista de produtos não desperdicados enviada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutosNaoDesperdicados'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutosNaoDesperdicados'
        "400":
          description: Erro ao enviar a lista
        "404":
          description: Não existe produtos na base de dados
      x-swagger-router-controller: Produto
  /produto/associarProdutoUtilizador:
    post:
      tags:
      - produto
      summary: Associar um produto ao cliente
      description: Associar um ou mais produtos a lista de favoritos do cliente
      operationId: postAssociarProdutoCliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssociarProdutoCliente'
          application/xml:
            schema:
              $ref: '#/components/schemas/AssociarProdutoCliente'
      responses:
        "200":
          description: Associação feita com sucesso
        "400":
          description: Erro
        "404":
          description: Utilizador invalido
      security:
      - bearerAuth: []
      x-swagger-router-controller: Produto
  /produto/associarProdutoUtilizador/{utilizadorId}:
    get:
      tags:
      - produto
      summary: Listar produtos favoritos do utilizador
      description: Lista com algum detalhe os produtos favoritos do utilizador
      operationId: getListarAssociarProdutoUtilizador
      parameters:
      - name: utilizadorId
        in: path
        description: É necessário o envio do utilizadorId para puder ser enviado a
          lista de produtos correta
        required: true
        style: simple
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Enviada a lista com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaProdutosAssociados'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListaProdutosAssociados'
        "400":
          description: Erro
        "404":
          description: Utilizador não foi encontrado
      security:
      - bearerAuth: []
      x-swagger-router-controller: Produto
  /utilizador:
    get:
      tags:
      - utilizador
      summary: Login do utilizador
      operationId: getUtilizador
      parameters:
      - name: utilizador
        in: query
        description: nome do utilizador
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: palavra passe do utilizador
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Utilizador logado com sucesso
        "400":
          description: Utilizador invalido
      x-swagger-router-controller: Utilizador
    post:
      tags:
      - utilizador
      summary: Criar utilizador
      description: Criação de um novo utilizador
      operationId: postUtilizador
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilizador'
          application/xml:
            schema:
              $ref: '#/components/schemas/Utilizador'
        required: true
      responses:
        "200":
          description: Utilizador criado com sucesso
        "400":
          description: Erro na criacao de um utilizador
      x-swagger-router-controller: Utilizador
  /utilizador/logout:
    get:
      tags:
      - utilizador
      summary: Logout do utilizador
      operationId: logoutUtilizador
      responses:
        "200":
          description: Logout efetuado com sucesso
      security:
      - bearerAuth: []
      x-swagger-router-controller: Utilizador
  /utilizador/{email}:
    get:
      tags:
      - utilizador
      summary: Encontrar utilizador
      operationId: getUtilizadorByEmail
      parameters:
      - name: email
        in: path
        description: Necessário enviar o email do utilizador pretendido
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Enviado utilizador coom sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
            application/xml:
              schema:
                $ref: '#/components/schemas/Utilizador'
        "400":
          description: Erro ao enviar o utilizador
        "404":
          description: Utilizador não encontrado
      security:
      - bearerAuth: []
      x-swagger-router-controller: Utilizador
    delete:
      tags:
      - utilizador
      summary: Eliminar utilizador
      description: So consegue ser realizado por um utilizador logado
      operationId: deleteUtilizador
      parameters:
      - name: email
        in: path
        description: email necessário
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Eliminado com sucesso
        "400":
          description: Erro
        "404":
          description: Utilizador não encontrado
      security:
      - bearerAuth: []
      x-swagger-router-controller: Utilizador
    patch:
      tags:
      - utilizador
      summary: Updated utilizador
      description: So consegue ser realizado por um utilizador logado
      operationId: patchUtilizador
      parameters:
      - name: email
        in: path
        description: email do utilizador necessário
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilizador'
          application/xml:
            schema:
              $ref: '#/components/schemas/Utilizador'
        required: true
      responses:
        "200":
          description: Atualizado utilizador com sucesso
        "400":
          description: Erro ao atualizar
        "404":
          description: Utilizador não foi encontrado
      security:
      - bearerAuth: []
      x-swagger-router-controller: Utilizador
components:
  schemas:
    Produto:
      required:
      - categoria
      - codigoBarras
      - data
      - informacao
      - informacaoNutricional
      - nome
      - nutricaoPontuacao
      - origem
      - percentagemDesconto
      - precoKilo
      - precoPromocional
      - precoUnitario
      - produtoId
      type: object
      properties:
        produtoId:
          type: integer
        nome:
          type: string
        categoria:
          $ref: '#/components/schemas/Categoria'
        informacao:
          $ref: '#/components/schemas/Informacao'
        precoUnitario:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        precoPromocional:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        percentagemDesconto:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        precoKilo:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        informacaoNutricional:
          $ref: '#/components/schemas/InformacaoNutricional'
        origem:
          type: string
        nutricaoPontuacao:
          type: string
        data:
          $ref: '#/components/schemas/Data'
        codigoBarras:
          type: integer
      example:
        precoUnitario: 0.59621339166831821554382031536079011857509613037109375
        precoPromocional: 0.5637376656633328320111786524648778140544891357421875
        produtoId: 0
        percentagemDesconto: 0.23021358869347652298387174596427939832210540771484375
        data:
          dataValidade: dataValidade
          dataProducao: dataProducao
          id: 7
        categoria:
          name: name
          id: 6
        origem: origem
        nome: nome
        precoKilo: 0.7061401241503109105224211816675961017608642578125
        informacao:
          informacaoCurta: informacaoCurta
          informacaoComprida: informacaoComprida
          id: 1
        nutricaoPontuacao: nutricaoPontuacao
        informacaoNutricional:
          hidratosDeCarbono: 0.1231513536777255612975068288506008684635162353515625
          peso: 0
          energia: 0.2027123023002321833274663731572218239307403564453125
          saturados: 0.7386281948385884366103937281877733767032623291015625
          proteina: 0.1489415909854170383397331534069962799549102783203125
          id: 9
          lipidos: 0.4145608029883935952142337555414997041225433349609375
          acucar: 0.1024645700144157789424070870154537260532379150390625
          sal: 0.68468526983526400986335147536010481417179107666015625
        codigoBarras: 1
      xml:
        name: Produto
    Informacao:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
        informacaoCurta:
          maxLength: 150
          type: string
        informacaoComprida:
          type: string
      example:
        informacaoCurta: informacaoCurta
        informacaoComprida: informacaoComprida
        id: 1
      xml:
        name: informacao
    Detalhe:
      required:
      - codigo
      - descricao
      - id
      - nome
      - precoKilo
      - precoUnitario
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        codigo:
          type: integer
        precoUnitario:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        precoKilo:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
      example:
        precoUnitario: 0.5637376656633328320111786524648778140544891357421875
        codigo: 5
        nome: nome
        id: 1
        precoKilo: 0.23021358869347652298387174596427939832210540771484375
        descricao: descricao
      xml:
        name: detalhe
    Categoria:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        name: name
        id: 6
      xml:
        name: Categoria
    InformacaoNutricional:
      required:
      - acucar
      - energia
      - hidratosDeCarbono
      - id
      - lipidos
      - peso
      - proteina
      type: object
      properties:
        id:
          type: integer
        peso:
          minimum: 0
          exclusiveMinimum: true
          type: integer
        energia:
          minimum: 0
          type: number
          format: double
        lipidos:
          minimum: 0
          type: number
          format: double
        saturados:
          minimum: 0
          type: number
          format: double
        hidratosDeCarbono:
          minimum: 0
          type: number
          format: double
        acucar:
          minimum: 0
          type: number
          format: double
        proteina:
          minimum: 0
          type: number
          format: double
        sal:
          minimum: 0
          type: number
          format: double
      example:
        hidratosDeCarbono: 0.1231513536777255612975068288506008684635162353515625
        peso: 0
        energia: 0.2027123023002321833274663731572218239307403564453125
        saturados: 0.7386281948385884366103937281877733767032623291015625
        proteina: 0.1489415909854170383397331534069962799549102783203125
        id: 9
        lipidos: 0.4145608029883935952142337555414997041225433349609375
        acucar: 0.1024645700144157789424070870154537260532379150390625
        sal: 0.68468526983526400986335147536010481417179107666015625
      xml:
        name: informacaoNutricional
    Data:
      required:
      - dataProducao
      - dataValidade
      - id
      type: object
      properties:
        id:
          type: integer
        dataValidade:
          pattern: "/([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/"
          type: string
        dataProducao:
          pattern: "/([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/"
          type: string
      example:
        dataValidade: dataValidade
        dataProducao: dataProducao
        id: 7
      xml:
        name: data
    ListaPrecoMedio:
      minItems: 0
      type: array
      xml:
        name: ListaPrecoMedio
      items:
        $ref: '#/components/schemas/ListaPrecoMedio_inner'
    ListaProdutos:
      minItems: 0
      required:
      - produto
      type: array
      xml:
        name: Produto
      items:
        $ref: '#/components/schemas/ListaProdutos_inner'
    AssociarProdutoCliente:
      required:
      - utilizadorId
      type: object
      properties:
        utilizadorId:
          type: integer
        listaProduto:
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/AssociarProdutoCliente_listaProduto'
      xml:
        name: AssociarProdutoCliente
    ListaProdutosAssociados:
      required:
      - utilizadorId
      type: object
      properties:
        utilizadorId:
          type: integer
        listaProduto:
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/ListaProdutosAssociados_listaProduto'
      example:
        listaProduto:
        - produto:
            precoUnitario: 0.5637376656633328320111786524648778140544891357421875
            codigo: 5
            nome: nome
            id: 1
            precoKilo: 0.23021358869347652298387174596427939832210540771484375
            descricao: descricao
        - produto:
            precoUnitario: 0.5637376656633328320111786524648778140544891357421875
            codigo: 5
            nome: nome
            id: 1
            precoKilo: 0.23021358869347652298387174596427939832210540771484375
            descricao: descricao
        utilizadorId: 0
      xml:
        name: ListaProdutosAssociados
    ListaProdutosNaoDesperdicados:
      minItems: 0
      type: array
      xml:
        name: ListaProdutosNaoDesperdicados
      items:
        $ref: '#/components/schemas/ListaProdutosNaoDesperdicados_inner'
    Utilizador:
      required:
      - apelido
      - email
      - nome
      - password
      - tipo
      type: object
      properties:
        tipo:
          type: string
          enum:
          - utilizador
          - admin
        nome:
          type: string
        apelido:
          type: string
        email:
          type: string
          format: email
          example: user@exemple.com
        password:
          type: string
        contacto:
          pattern: "[9]{1}[0-9]{2}[0-9]{3}[0-9]{3}$"
          type: string
      example:
        tipo: utilizador
        password: password
        contacto: contacto
        apelido: apelido
        nome: nome
        email: user@exemple.com
      xml:
        name: Utilizador
    Login:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@exemple.com
        password:
          type: string
      xml:
        name: Login
    ListaPrecoMedio_inner:
      required:
      - precoMedio
      - produtoId
      type: object
      properties:
        produtoId:
          type: integer
        precoMedio:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        detalhe:
          $ref: '#/components/schemas/Detalhe'
      example:
        produtoId: 0
        precoMedio: 0.602745618307040320615897144307382404804229736328125
        detalhe:
          precoUnitario: 0.5637376656633328320111786524648778140544891357421875
          codigo: 5
          nome: nome
          id: 1
          precoKilo: 0.23021358869347652298387174596427939832210540771484375
          descricao: descricao
    ListaProdutos_inner:
      type: object
      properties:
        produto:
          $ref: '#/components/schemas/Produto'
      example:
        produto:
          precoUnitario: 0.59621339166831821554382031536079011857509613037109375
          precoPromocional: 0.5637376656633328320111786524648778140544891357421875
          produtoId: 0
          percentagemDesconto: 0.23021358869347652298387174596427939832210540771484375
          data:
            dataValidade: dataValidade
            dataProducao: dataProducao
            id: 7
          categoria:
            name: name
            id: 6
          origem: origem
          nome: nome
          precoKilo: 0.7061401241503109105224211816675961017608642578125
          informacao:
            informacaoCurta: informacaoCurta
            informacaoComprida: informacaoComprida
            id: 1
          nutricaoPontuacao: nutricaoPontuacao
          informacaoNutricional:
            hidratosDeCarbono: 0.1231513536777255612975068288506008684635162353515625
            peso: 0
            energia: 0.2027123023002321833274663731572218239307403564453125
            saturados: 0.7386281948385884366103937281877733767032623291015625
            proteina: 0.1489415909854170383397331534069962799549102783203125
            id: 9
            lipidos: 0.4145608029883935952142337555414997041225433349609375
            acucar: 0.1024645700144157789424070870154537260532379150390625
            sal: 0.68468526983526400986335147536010481417179107666015625
          codigoBarras: 1
    AssociarProdutoCliente_listaProduto:
      required:
      - produtoId
      type: object
      properties:
        produtoId:
          type: integer
    ListaProdutosAssociados_listaProduto:
      required:
      - produto
      type: object
      properties:
        produto:
          $ref: '#/components/schemas/Detalhe'
      example:
        produto:
          precoUnitario: 0.5637376656633328320111786524648778140544891357421875
          codigo: 5
          nome: nome
          id: 1
          precoKilo: 0.23021358869347652298387174596427939832210540771484375
          descricao: descricao
    ListaProdutosNaoDesperdicados_inner:
      required:
      - mediaDesconto
      - nome
      - pesoLiquidoNaoDesperdicado
      - produtoId
      - quantidadeNaoDesperdicada
      - valorPoupado
      properties:
        produtoId:
          type: integer
        nome:
          type: string
        valorPoupado:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        quantidadeNaoDesperdicada:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        pesoLiquidoNaoDesperdicado:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
        mediaDesconto:
          minimum: 0
          exclusiveMinimum: true
          type: number
          format: double
      example:
        produtoId: 0
        mediaDesconto: 0.5637376656633328320111786524648778140544891357421875
        valorPoupado: 0.602745618307040320615897144307382404804229736328125
        quantidadeNaoDesperdicada: 0.146581298050294517310021547018550336360931396484375
        nome: nome
        pesoLiquidoNaoDesperdicado: 0.59621339166831821554382031536079011857509613037109375
  requestBodies:
    Produto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Produto'
        application/xml:
          schema:
            $ref: '#/components/schemas/Produto'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
